# Setup
title: onlyjams
url: https://onlyjamsradio.com
paginate: 3
baseurl: ""
permalink: pretty

paginate_path: "page:num/"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: OnlyJams
  url: https://onlyjamsradio.com
  email: contactus@onlyjamsradio.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: all
    url: /archive

  - title: about
    url: /about

  - title: twitch
    url: /twitch

  - title: finds
    url: /music_finds

  - title: shows
    url: /radio_shows
